title: Lengte van een noot
hero_image: images/banner.png
description: Instructies voor het wijzigen van de lengte van een noot in MicroPython met behulp van picozero
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - 
    title: Lengte van een noot
